worlds:
    chozo tech server start:
    - U43ME14ZW
    - 6ZHIWSOFT
    - X7SZW9UI1
    - AHILXEV9A
    - MAQ0Y738L
    - 9VJNZ0ARM
    - NF0UJTY8M
    - H7RMWLEU9
    - V1TRMD7MF
    - H99L6VYL1
    - V98XDWT4I
