# ===--- Locator --------------------------------------------------------------------------------------------------=== #
#
#    Quickly locate containers, ores, spawners and entities
#
# ===------------------------------------------------------------------------------------------------ © Hexosse ---=== #


# Spawner renderer
spawners:
  enable: true
  default:
    enable: true
    code: Default
    short:
      distance: 1.5
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x20_82_00_AF'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x20_82_00_AF'
    close:
      distance: 8.0
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x40_82_00_AF'
      faceColor: '0x1C_82_00_AF'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x40_82_00_AF'
    far:
      distance: 16.0
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x80_82_00_AF'
      faceColor: '0x80_82_00_AF'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x80_82_00_AF'
  blaze:
    enable: true
    code: Blaze
    short:
      distance: 1.5
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x20_FF_FF_1C'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x20_FF_FF_1C'
    close:
      distance: 8.0
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x40_FF_FF_1C'
      faceColor: '0x1C_FF_FF_1C'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x40_FF_FF_1C'
    far:
      distance: 16.0
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x80_FF_FF_1C'
      faceColor: '0x80_FF_FF_1C'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x80_FF_FF_1C'
  caveSpider:
    enable: false
    code: CaveSpider
    short:
      distance: 1.5
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x20_82_00_AF'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x20_82_00_AF'
    close:
      distance: 8.0
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x40_82_00_AF'
      faceColor: '0x1C_82_00_AF'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x40_82_00_AF'
    far:
      distance: 16.0
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x80_82_00_AF'
      faceColor: '0x80_82_00_AF'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x80_82_00_AF'
  skeleton:
    enable: false
    code: Skeleton
    short:
      distance: 1.5
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x20_82_00_AF'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x20_82_00_AF'
    close:
      distance: 8.0
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x40_82_00_AF'
      faceColor: '0x1C_82_00_AF'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x40_82_00_AF'
    far:
      distance: 16.0
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x80_82_00_AF'
      faceColor: '0x80_82_00_AF'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x80_82_00_AF'
  spider:
    enable: true
    code: Spider
    short:
      distance: 1.5
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x20_82_00_AF'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x20_82_00_AF'
    close:
      distance: 8.0
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x40_82_00_AF'
      faceColor: '0x1C_82_00_AF'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x40_82_00_AF'
    far:
      distance: 16.0
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x80_82_00_AF'
      faceColor: '0x80_82_00_AF'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x80_82_00_AF'
  zombie:
    enable: true
    code: Zombie
    short:
      distance: 1.5
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x20_82_00_AF'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x20_82_00_AF'
    close:
      distance: 8.0
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x40_82_00_AF'
      faceColor: '0x1C_82_00_AF'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x40_82_00_AF'
    far:
      distance: 16.0
      mainEdgeWidth: 2.5
      mainEdgeColor: '0x80_82_00_AF'
      faceColor: '0x80_82_00_AF'
      outlineEdgeWidth: 1.0
      outlineEdgeColor: '0x80_82_00_AF'

enable: true
